server:
   port: 7002
spring:
   application:
      name: eureka-client-produce
   datasource:
      username: root
      password: root123
      url: jdbc:mysql://106.14.247.199:3306/lyh?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      
eureka:
   client:
      service-url:    
         defaultZone: http://localhost:7001/eureka/
   instance:
      hostname: localhost
      # 显示端口和ip信息
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      
         