server:
   port: 7002
spring:
   application:
      name: eureka-client-produce
      
eureka:
   client:
      service-url:    
         defaultZone: http://localhost:7001/eureka/
   instance:
      hostname: localhost
      # 显示端口和ip信息
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      
         