spring:
   # DataSource Config
   datasource:
      username: root
      password: root123
      url: jdbc:mysql://106.14.247.199:3306/learn?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver




eureka:
   client:
      # 访问Eureka服务端的地址
      service-url:
         defaultZone: http://localhost:7001/eureka/
