server:
   port: 7002
spring:
   application:
      name: notice-server

eureka:
   client:
      service-url:    
         defaultZone: http://106.14.247.199:7001/eureka/
   instance:
      hostname: notice-server
      # 显示端口和ip信息
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}