server:
   port: 7001
spring:
   application:
      name: eureka-server
      
eureka:
   client:
      register-with-eureka: false      #  让自己不需要去注册自己, 服务中心暂时还不需要
      fetch-registry: false # fetch-registy 不去扫描服务
      service-url:  # 覆盖默认地址,否则会一直访问8761端口
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   # 设置Eureka的名字
   instance:
      hostname: eurekaServer